Update support for Laravel Framework v9
datacreativa/laravel-presentable pull request #3
Opened 2022-02-15 05:29 UTC by zaratedev

@ErickZH 

Review this update, please!

2022-02-17 04:15 UTC, ErickZH requested changes

2022-02-17 04:15 UTC, ErickZH commented on .github/workflows/main.yml
> +            php-version: 8.0
Change to php 8.1

2022-02-17 04:15 UTC, ErickZH commented on CHANGELOG.md
> +- Update support for Laravel Framework v9
Add new line

2022-02-17 04:15 UTC, ErickZH commented on composer.json
> +        "php": "^8.0",
Change to php 8.1

2022-02-17 04:15 UTC, ErickZH commented on README.md
> +| 9       | 0.2     |
Why not 0.0.2 ?

2022-03-09 05:35 UTC, merged

2022-03-09 19:09 UTC, zaratedev commented
@ErickZH Can you create the tag release?

2022-03-09 19:15 UTC, ErickZH commented
@zaratedev ready!